# Generated by Django 4.2.1 on 2023-06-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Mathematics',
        ),
    ]
